const CLIENTS = [
  "lostsaintsmusic",
  "ashlieamberofficial",
  "thesummitband",
  "timharpermusic",
  "acidhawkband",
  "ariaanjali",
  "krismyersdrums",
  "kittwakeley",
  "soleoceanna",
  "acncountry",
  "happylandingxo",
  "vaya.vaya_am",
  "droolingpianoguys",
  "theromancemusic",
  "billy.moran",
  "anselbrownmusic",
  "devongilfillian",
  "tylerlorettee",
  "theelliotposton",
  "shaneweisman",
  "thebandsolstice",
  "hickory_music",
  "joeymyronmusic",
  "alyssateppermusic",
  "goodtimercrds",
  "grayscalepa",
  "taylorhicksofficial",
  "toofinerecords",
  "lanitasmith",
  "admiral.radio",
  "nightacclaimmusic",
  "thedirtyguvnahs",
  "peterkeys",
  "tylerbooner",
];

module.exports = { CLIENTS };
